### ISSUE TITLE
When use now db return Error 1292: Incorrect datetime value

### ISSUE THREAD

**Issue by howie** [gobuffalo/suite#31]
When I try to use 
`
created_at` = "<%= now() %>"
`
DB return  
`
Error 1292: Incorrect datetime value: '2020-01-07T17:26:54+08:00' for column 'created_at' at row 1
`
The format should be 2019-09-01 12:38:52

**Comment by paganotoni** [comment]
This one depends on how plush is configured to render the date, closing this one given there was not much activity, feel free to reopen if still relevant.
