### ISSUE TITLE
[Model]: Deadlock using postgres

### ISSUE THREAD

**Issue by Haimi** [gobuffalo/suite#32]
When using a `ModelSuite` like in the documentation and create multiple tests using fixtures with a postgres database, I get a deadlock leading to a 10 minutes timeout. 

Looking into the postgres database, I was able to find a lot of statements created by the `postgresql.TruncateAll` method.

I followed the problem a little further:
* As the Tests are _initialized_ in parallel, the `SetupTest` methods of all tests are executed in parallel
* So, for every Test, the `TruncateAll` is executed at once
* As the command created by the postgres dialect module executed a SQL `TRUNCATE` command for every table in the DB
* `TRUNCATE` commands in psql create exclusive locks, which leads to a deadlock.

I found [a solution suggesting using DELETE instead of TRUNCATE](https://dba.stackexchange.com/questions/66445/truncate-in-transaction-dead-lock#answer-81948) as a possible solution for this, which might resolve the deadlock, but still will lead to unexpected behaviour due to the parallel running `SetupTest` executions.

Any Idea how to solve this? Any suggestions for workarounds?

Additionally: I cannot find any model unit test examples. Are there any available somewhere or has this not been considered yet?

Thank you in advance.

**Comment by corylanou** [comment]
I'm also seeing this in our code after I updated to the latest version.  It runs fine locally, but on github it deadlocks every time.

**Comment by ironsalsa** [comment]
I'm experiencing this as well - this makes it impossible to run tests more than one at a time.
