### ISSUE TITLE
Cannot use pop v5 with suite.

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/suite#35]
It seems Suite depends on a version of 0-version of pop. That causes that we cannot use pop v5 with it, I think we should make that `pop.Connection` an interface in here or launch a new version that depends on pop v5.

@gobuffalo/all, thoughts?

**Comment by hdm** [comment]
interface is likely the best option for the long haul

**Comment by paganotoni** [comment]
Right, I started doing the homework and noticed this would imply 3 interfaces:

- One for the connection
- One for validate.Errors (some of the methods return it)
- One for Query

Most of these have a long list of methods :D

**Comment by paganotoni** [comment]
see here https://pkg.go.dev/github.com/gobuffalo/pop/v5?tab=doc

**Comment by hdm** [comment]
good point, its going to be huge, would it be better to focus on v5 as the long-term interface?

**Comment by paganotoni** [comment]
Putting together a Draft in here so we both can try it, we can decide later if this is not the best place.

**Comment by paganotoni** [comment]
ok. After expending like an hour on putting it together I noticed I ended up with like 6 Interfaces, then noticed this repo is not even using modules. 😅

**Comment by paganotoni** [comment]
Closing this one. For the record we ended up making v3 depend on pop/v5. This will come back once pop does a major version change.
