### ISSUE TITLE
Is there a way to run an individual test from a suite?

### ISSUE THREAD

**Issue by arschles** [gobuffalo/suite#5]
I'm looking to do something similar to `go run -test.run=TestABC`. Does suite or the `buffalo` CLI look for a flag like `test.run`?

**Comment by markbates** [comment]
```
$ buffalo test -m "Some_Words"
```

https://gobuffalo.io/docs/testing#running-tests
https://blog.gobuffalo.io/buffalo-v0-10-2-released-9427d0d5eec4
